// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSpark.ArtSpark.Demo.Data;

#nullable disable

namespace WebSpark.ArtSpark.Demo.Migrations
{
    [DbContext(typeof(ArtSparkDbContext))]
    [Migration("20250117000000_PopulateCollectionSlugs")]
    partial class PopulateCollectionSlugs
    {        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only updates data, no schema changes
            // Model structure remains unchanged from previous migration
        }
    }
}
